### ISSUE TITLE
Networking is broken with latest clearlinux 

### ISSUE THREAD

**Issue by mcastelino** [clearlinux/cloud-native-setup#102] opened 2019-06-20 23:28 UTC
Due to `systemd` changes in `rp_filter` all non local traffic to the pods is blocked. 

The canal setup has not changed,  so it must be either the kernel or systemd.

This can be worked around by setting FELIX_IGNORELOOSERPF to true. 

```
diff --git a/clr-k8s-examples/0-canal/canal.yaml b/clr-k8s-examples/0-canal/canal.yaml
index 6666a2c..17b3cd4 100644
--- a/clr-k8s-examples/0-canal/canal.yaml
+++ b/clr-k8s-examples/0-canal/canal.yaml
@@ -159,6 +159,8 @@ spec:
               value: "info"
             - name: FELIX_HEALTHENABLED
               value: "true"
+            - name: FELIX_IGNORELOOSERPF
+              value: "true"
           securityContext:
             privileged: true
           resources:
diff --git a/clr-k8s-examples/setup_system.sh b/clr-k8s-examples/setup_system.sh
index f1614bf..4f00498 100755
--- a/clr-k8s-examples/setup_system.sh
+++ b/clr-k8s-examples/setup_system.sh
@@ -22,8 +22,6 @@ fi
 sudo mkdir -p /etc/sysctl.d/
 cat <<EOT | sudo bash -c "cat > /etc/sysctl.d/60-k8s.conf"
 net.ipv4.ip_forward=1
-net.ipv4.conf.default.rp_filter=1
-net.ipv4.conf.all.rp_filter=1
 EOT
 sudo systemctl restart systemd-sysctl
```

/cc @krsna1729

**Comment by mcastelino** [comment] 2019-06-21 16:46
Looks like this is still does not fix it.

**Comment by mcastelino** [comment] 2019-06-25 02:02
This may be a crio or crio configuration issue. k3s (i.e. containerd with flannel) works fine on Clearlinux.

**Comment by krsna1729** [comment] 2019-06-25 04:57
```
clear@clr-01 ~/clr-k8s-examples $ swupd info
Installed version: 29880
clear@clr-01 ~/clr-k8s-examples $ crio --version
crio version 1.14.1
commit: ""
clear@clr-01 ~/clr-k8s-examples $ /lib/systemd/systemd --version
systemd 241 (241)
+PAM +AUDIT -SELINUX +IMA -APPARMOR -SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 -IDN -PCRE2 default-hierarchy=legacy
clear@clr-01 ~/clr-k8s-examples $ kubectl create deployment nginx --image=nginx
deployment.apps/nginx created
clear@clr-01 ~/clr-k8s-examples $ kubectl scale --replicas=3 deployment nginx
deployment.extensions/nginx scaled
clear@clr-01 ~/clr-k8s-examples $ for i in $(kubectl get pod -l app=nginx -o jsonpath='{.items[*].status.podIP}'); do curl -s -o /dev/null -w "%{http_code}\n" $i;  done
200
200
200
clear@clr-01 ~/clr-k8s-examples $ sysctl -ar '\.rp_filter'
net.ipv4.conf.all.rp_filter = 2
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.enp0s8.rp_filter = 0
net.ipv4.conf.enp0s9.rp_filter = 0
net.ipv4.conf.flannel/1.rp_filter = 1
net.ipv4.conf.lo.rp_filter = 0
```

**Comment by krsna1729** [comment] 2019-06-25 04:57
```
clear@clr-01 ~/clr-k8s-examples $ swupd info
Installed version: 29890
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update
clear@clr-01 ~/clr-k8s-examples $ crio --version
crio version 1.14.2
commit: ""
clear@clr-01 ~/clr-k8s-examples $ /lib/systemd/systemd --version
systemd 242 (242)
+PAM +AUDIT -SELINUX +IMA -APPARMOR -SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 -IDN -PCRE2 default-hierarchy=legacy
clear@clr-01 ~/clr-k8s-examples $ kubectl create deployment nginx --image=nginx
deployment.apps/nginx created
clear@clr-01 ~/clr-k8s-examples $ kubectl scale --replicas=3 deployment nginx
deployment.extensions/nginx scaled
clear@clr-01 ~/clr-k8s-examples $ for i in $(kubectl get pod -l app=nginx -o jsonpath='{.items[*].status.podIP}'); do curl -s -o /dev/null -w "%{http_code}\n" $i;  done

^C
clear@clr-01 ~/clr-k8s-examples $ sysctl -ar '\.rp_filter'
net.ipv4.conf.all.rp_filter = 2
net.ipv4.conf.cali2b86df72b07.rp_filter = 1
net.ipv4.conf.caliacd620db126.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.enp0s8.rp_filter = 0
net.ipv4.conf.enp0s9.rp_filter = 0
net.ipv4.conf.flannel/1.rp_filter = 1
net.ipv4.conf.lo.rp_filter = 0
```

**Comment by krsna1729** [comment] 2019-06-25 04:58
version 29890 is where it fails and two changes took place here
crio 1.14.1 to 1.14.2
systemd 241 to 242

**Comment by NitinAtIntel** [comment] 2019-08-08 18:48
@mcastelino just to confirm, would attempting to access a service in a pod via ingress be a good test for reproduction?

**Comment by NitinAtIntel** [comment] 2019-08-08 23:48
@mcastelino @krsna1729 I am able to create a simple http-echo service and an ingress to route requests to it.  From outside the cluster I can use the IP address of the master node with the NodePort for the ingress-nginx service created by our stack.   I can get a response.  I tried alternative URLs and successfully received 404s.  So at this stage it looks like the workaround of:
`+            - name: FELIX_IGNORELOOSERPF
+              value: "true"`
Is working.
I assume, however that we don't want this to remain the case and want to enable rp filtering prior to closing this issue, yes?

**Comment by krsna1729** [comment] 2019-08-09 00:36
correct. if we can go back to working sysctl rp filter and remove FELIX_IGNORELOOSERPF, you can close then.

**Comment by NitinAtIntel** [comment] 2019-08-14 22:21
Here are details on the rp_filter settings:
```
rp_filter - INTEGER
    0 - No source validation.
    1 - Strict mode as defined in RFC3704 Strict Reverse Path
        Each incoming packet is tested against the FIB and if the interface
        is not the best reverse path the packet check will fail.
        By default failed packets are discarded.
    2 - Loose mode as defined in RFC3704 Loose Reverse Path
        Each incoming packet's source address is also tested against the FIB
        and if the source address is not reachable via any interface
        the packet check will fail.

    Current recommended practice in RFC3704 is to enable strict mode
    to prevent IP spoofing from DDos attacks. If using asymmetric routing
    or other complicated routing, then loose mode is recommended.

    The max value from conf/{all,interface}/rp_filter is used
    when doing source validation on the {interface}.

    Default value is 0. Note that some distributions enable it
    in startup scripts.
```

The difference between setting 1 and 2 is essentially if the source address is reachable via the incoming interface vs any interface, respectively.

There is a discussion here at projectcalico: https://github.com/projectcalico/calicoctl/issues/1082.
In that discussion this snippet is referenced from the Felix code itself:
```
# For IPv4, we rely on the kernel's reverse path filtering to prevent
# workloads from spoofing their IP addresses.
#
# The RPF check for a particular interface is controlled by several
# sysctls:
#
# - ipv4.conf.all.rp_filter is a global override
# - ipv4.conf.default.rp_filter controls the value that is set on a newly
#   created interface
# - ipv4.conf.<interface>.rp_filter controls a particular interface.
#
# The algorithm for combining the global override and per-interface values
# is to take the *numeric* maximum between the two.  The values are:
# 0=off, 1=strict, 2=loose.  "loose" is not suitable for Calico since it
# would allow workloads to spoof packets from other workloads on the same
# host.  Hence, we need the global override to be <=1 or it would override
# the per-interface setting to "strict" that we require.
#
# We bail out rather than simply setting it because setting 2, "loose",
# is unusual and it is likely to have been set deliberately.
```

Eventually, the discussion ends with the agreement to add `FELIX_IGNORELOOSERPF`, although the preferred setup is to use the recommended setting of 1 rather than 2.

Additionally, this recent issue from coreos https://github.com/coreos/fedora-coreos-tracker/issues/219 gets to the cause of the rp filter value change and it is systemd 240.  The discussion there indicates a preference for using os defaults (in this case, supporting rp_filter=2).  That results in the issue bouncing back to projectcalico just *27* days ago: https://github.com/projectcalico/felix/issues/2082, where the a projectcalcio developer has said it is not a great default to have set.

Given this, we have two choices: clear linux could change the setting back to 1 or we leave `FELIX_IGNORELOOSERPF` in place.  In either case, I can ping projectcalico in issue 2082.  Thoughts?

**Comment by ganeshmaharaj** [comment] 2019-08-15 02:14
I believe we have changed rp_filter in the past ( see https://github.com/clearlinux/cloud-native-setup/commit/d31d78c19302f8098a16adc5ff9f9708bcd82b9e ). If there is a way we can close this out temporarily, I am open to that change.

**Comment by NitinAtIntel** [comment] 2019-08-15 06:04
In this case, 1 is actually a more secure setting.  The only issue is that systemd seems to default the setting to 2 now..  So whether we change it to 1 in setup_system or clear changes it in the distro, unless we get systemd to change it back to 1 I think our change would need to remain for the foreseeable future.

**Comment by ganeshmaharaj** [comment] 2019-08-15 14:00
Let us assume that clear is not going to change any of their defaults. I think we can add the change in setup_system with a note to the calico thread and get past this issue for now. We can roll it back later once upstreams settle down on the right fix.

**Comment by NitinAtIntel** [comment] 2019-08-15 21:02
PR #147

**Comment by NitinAtIntel** [comment] 2019-08-16 05:50
Closing per discussion and PR #147

**Closed by NitinAtIntel** 2019-08-16 05:50 UTC
